language: python

services:
  - docker

before_install:
#  - docker build -t hello act_1-2/
#  - docker run -d -p 8000:80 hello
  - docker-compose up -d

install:
  - pip install -r test/requirements.txt

script:
  - pytest
